// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js'

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://truyxgamywbkuovyzlhe.supabase.co"
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRydXl4Z2FteXdia3Vvdnl6bGhlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NDUwMDksImV4cCI6MjA2ODQyMTAwOX0.3gkSA88dIlZrPMJfLA5CZ7O3HOSrmhJrMUdLGmKjLkI'

export const supabase = createClient(supabaseUrl, supabaseAnonKey)